// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: uber/cadence/api/v1/service_semaphore.proto

package apiv1

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// SemaphoreAPIYARPCClient is the YARPC client-side interface for the SemaphoreAPI service.
type SemaphoreAPIYARPCClient interface {
	CreateSemaphore(context.Context, *CreateSemaphoreRequest, ...yarpc.CallOption) (*CreateSemaphoreResponse, error)
}

func newSemaphoreAPIYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) SemaphoreAPIYARPCClient {
	return &_SemaphoreAPIYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.cadence.api.v1.SemaphoreAPI",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewSemaphoreAPIYARPCClient builds a new YARPC client for the SemaphoreAPI service.
func NewSemaphoreAPIYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) SemaphoreAPIYARPCClient {
	return newSemaphoreAPIYARPCClient(clientConfig, nil, options...)
}

// SemaphoreAPIYARPCServer is the YARPC server-side interface for the SemaphoreAPI service.
type SemaphoreAPIYARPCServer interface {
	CreateSemaphore(context.Context, *CreateSemaphoreRequest) (*CreateSemaphoreResponse, error)
}

type buildSemaphoreAPIYARPCProceduresParams struct {
	Server      SemaphoreAPIYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildSemaphoreAPIYARPCProcedures(params buildSemaphoreAPIYARPCProceduresParams) []transport.Procedure {
	handler := &_SemaphoreAPIYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.cadence.api.v1.SemaphoreAPI",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "CreateSemaphore",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.CreateSemaphore,
							NewRequest:  newSemaphoreAPIServiceCreateSemaphoreYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildSemaphoreAPIYARPCProcedures prepares an implementation of the SemaphoreAPI service for YARPC registration.
func BuildSemaphoreAPIYARPCProcedures(server SemaphoreAPIYARPCServer) []transport.Procedure {
	return buildSemaphoreAPIYARPCProcedures(buildSemaphoreAPIYARPCProceduresParams{Server: server})
}

// FxSemaphoreAPIYARPCClientParams defines the input
// for NewFxSemaphoreAPIYARPCClient. It provides the
// paramaters to get a SemaphoreAPIYARPCClient in an
// Fx application.
type FxSemaphoreAPIYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxSemaphoreAPIYARPCClientResult defines the output
// of NewFxSemaphoreAPIYARPCClient. It provides a
// SemaphoreAPIYARPCClient to an Fx application.
type FxSemaphoreAPIYARPCClientResult struct {
	fx.Out

	Client SemaphoreAPIYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxSemaphoreAPIYARPCClient provides a SemaphoreAPIYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  apiv1.NewFxSemaphoreAPIYARPCClient("service-name"),
//	  ...
//	)
func NewFxSemaphoreAPIYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxSemaphoreAPIYARPCClientParams) FxSemaphoreAPIYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxSemaphoreAPIYARPCClientResult{
			Client: newSemaphoreAPIYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxSemaphoreAPIYARPCProceduresParams defines the input
// for NewFxSemaphoreAPIYARPCProcedures. It provides the
// paramaters to get SemaphoreAPIYARPCServer procedures in an
// Fx application.
type FxSemaphoreAPIYARPCProceduresParams struct {
	fx.In

	Server      SemaphoreAPIYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxSemaphoreAPIYARPCProceduresResult defines the output
// of NewFxSemaphoreAPIYARPCProcedures. It provides
// SemaphoreAPIYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxSemaphoreAPIYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxSemaphoreAPIYARPCProcedures provides SemaphoreAPIYARPCServer procedures to an Fx application.
// It expects a SemaphoreAPIYARPCServer to be present in the container.
//
//	fx.Provide(
//	  apiv1.NewFxSemaphoreAPIYARPCProcedures(),
//	  ...
//	)
func NewFxSemaphoreAPIYARPCProcedures() interface{} {
	return func(params FxSemaphoreAPIYARPCProceduresParams) FxSemaphoreAPIYARPCProceduresResult {
		return FxSemaphoreAPIYARPCProceduresResult{
			Procedures: buildSemaphoreAPIYARPCProcedures(buildSemaphoreAPIYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: SemaphoreAPIReflectionMeta,
		}
	}
}

// SemaphoreAPIReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var SemaphoreAPIReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.cadence.api.v1.SemaphoreAPI",
	FileDescriptors: yarpcFileDescriptorClosure60f52eba354a86a4,
}

type _SemaphoreAPIYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_SemaphoreAPIYARPCCaller) CreateSemaphore(ctx context.Context, request *CreateSemaphoreRequest, options ...yarpc.CallOption) (*CreateSemaphoreResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "CreateSemaphore", request, newSemaphoreAPIServiceCreateSemaphoreYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*CreateSemaphoreResponse)
	if !ok {
		return nil, protobuf.CastError(emptySemaphoreAPIServiceCreateSemaphoreYARPCResponse, responseMessage)
	}
	return response, err
}

type _SemaphoreAPIYARPCHandler struct {
	server SemaphoreAPIYARPCServer
}

func (h *_SemaphoreAPIYARPCHandler) CreateSemaphore(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *CreateSemaphoreRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*CreateSemaphoreRequest)
		if !ok {
			return nil, protobuf.CastError(emptySemaphoreAPIServiceCreateSemaphoreYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.CreateSemaphore(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newSemaphoreAPIServiceCreateSemaphoreYARPCRequest() proto.Message {
	return &CreateSemaphoreRequest{}
}

func newSemaphoreAPIServiceCreateSemaphoreYARPCResponse() proto.Message {
	return &CreateSemaphoreResponse{}
}

var (
	emptySemaphoreAPIServiceCreateSemaphoreYARPCRequest  = &CreateSemaphoreRequest{}
	emptySemaphoreAPIServiceCreateSemaphoreYARPCResponse = &CreateSemaphoreResponse{}
)

var yarpcFileDescriptorClosure60f52eba354a86a4 = [][]byte{
	// uber/cadence/api/v1/service_semaphore.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
		0x10, 0xc5, 0x89, 0x7f, 0x8a, 0x5d, 0xb5, 0x85, 0x15, 0xdb, 0x92, 0x83, 0x94, 0x8a, 0x58, 0xa8,
		0xee, 0x92, 0x7a, 0xd4, 0x8b, 0xed, 0xc9, 0x8b, 0x84, 0xf4, 0x20, 0x78, 0x09, 0x9b, 0xcd, 0xd0,
		0x2e, 0x76, 0xb3, 0x6b, 0xb2, 0x09, 0x08, 0x7e, 0x14, 0x3f, 0xac, 0x34, 0x89, 0x5b, 0xff, 0xe4,
		0xe0, 0x71, 0xde, 0xfc, 0xde, 0xcc, 0x30, 0x0f, 0x4d, 0xf2, 0x08, 0x52, 0xca, 0x59, 0x0c, 0x09,
		0x07, 0xca, 0xb4, 0xa0, 0x85, 0x47, 0x33, 0x48, 0x0b, 0xc1, 0x21, 0xcc, 0x40, 0x32, 0xbd, 0x52,
		0x29, 0x10, 0x9d, 0x2a, 0xa3, 0xf0, 0xc9, 0x06, 0x26, 0x35, 0x4c, 0x98, 0x16, 0xa4, 0xf0, 0xdc,
		0xf3, 0xe6, 0x09, 0x3f, 0x9c, 0xa3, 0x0f, 0x07, 0xf5, 0xe6, 0x29, 0x30, 0x03, 0x8b, 0xaf, 0x4e,
		0x00, 0xaf, 0x39, 0x64, 0x06, 0xf7, 0x50, 0x2b, 0x56, 0x92, 0x89, 0x64, 0xe0, 0x0c, 0x9d, 0x71,
		0x3b, 0xa8, 0x2b, 0x7c, 0x81, 0x3a, 0x76, 0x4a, 0x98, 0x30, 0x09, 0x83, 0x9d, 0xb2, 0x7f, 0x6c,
		0xd5, 0x47, 0x26, 0x01, 0xbb, 0xe8, 0x80, 0x33, 0xcd, 0xb8, 0x30, 0x6f, 0x83, 0xdd, 0xa1, 0x33,
		0xde, 0x0f, 0x6c, 0x8d, 0x2f, 0x51, 0x37, 0xca, 0xf9, 0x0b, 0x98, 0xd0, 0x22, 0x7b, 0x25, 0xd2,
		0xa9, 0xe4, 0x79, 0xad, 0x8e, 0x9e, 0x50, 0xff, 0xcf, 0x75, 0x99, 0x56, 0x49, 0x06, 0xf8, 0x0e,
		0xb5, 0xed, 0xc2, 0xf2, 0xc2, 0xc3, 0xe9, 0x19, 0x69, 0xf8, 0x03, 0xd9, 0x5a, 0xb7, 0x86, 0xe9,
		0x3b, 0x3a, 0xb2, 0xfa, 0xbd, 0xff, 0x80, 0xd7, 0xa8, 0xfb, 0x6b, 0x11, 0x9e, 0x34, 0x4e, 0x6b,
		0x7e, 0x96, 0x7b, 0xf5, 0x3f, 0xb8, 0xba, 0x7d, 0x06, 0xa8, 0xcf, 0x95, 0x6c, 0xb2, 0xcc, 0x4e,
		0x2d, 0xbd, 0xa8, 0xc2, 0xf6, 0x37, 0x39, 0xf9, 0xce, 0xb3, 0xb7, 0x14, 0x66, 0x95, 0x47, 0x84,
		0x2b, 0x49, 0xbf, 0x27, 0x7b, 0x2d, 0xe2, 0x35, 0x5d, 0x2a, 0x5a, 0xe6, 0x59, 0xc7, 0x7c, 0xcb,
		0xb4, 0x28, 0xbc, 0xa8, 0x55, 0x6a, 0x37, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x5b, 0x3f,
		0x60, 0x4c, 0x02, 0x00, 0x00,
	},
	// uber/cadence/api/v1/semaphore.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x31, 0x4b, 0xc5, 0x30,
		0x14, 0x46, 0x89, 0xa2, 0xd8, 0x80, 0x15, 0xe2, 0x60, 0x71, 0x2a, 0x8a, 0xd8, 0xc5, 0x84, 0xe0,
		0xe8, 0x56, 0x77, 0x29, 0x75, 0x73, 0xb0, 0xdc, 0xa4, 0x97, 0x36, 0x68, 0x9a, 0x50, 0xd3, 0x8a,
		0xff, 0x5e, 0xda, 0xd7, 0x17, 0xde, 0xf0, 0xc6, 0x7b, 0x38, 0x17, 0xbe, 0x43, 0xef, 0x27, 0x85,
		0xa3, 0xd0, 0xd0, 0xe2, 0xa0, 0x51, 0x80, 0x37, 0x62, 0x96, 0xe2, 0x07, 0x2d, 0xf8, 0xde, 0x8d,
		0xc8, 0xfd, 0xe8, 0x82, 0x63, 0xd7, 0x8b, 0xc4, 0x37, 0x89, 0x83, 0x37, 0x7c, 0x96, 0x77, 0xbf,
		0x34, 0x79, 0xdf, 0x7b, 0xec, 0x81, 0xa6, 0xf1, 0xa9, 0x19, 0xc0, 0x62, 0x46, 0x72, 0x52, 0x24,
		0xf5, 0x65, 0xa4, 0x6f, 0x60, 0x91, 0xdd, 0xd2, 0x0b, 0x0d, 0x1e, 0xb4, 0x09, 0x7f, 0xd9, 0x49,
		0x4e, 0x8a, 0xb3, 0x3a, 0xde, 0xec, 0x91, 0x5e, 0xa9, 0x49, 0x7f, 0x61, 0x68, 0xa2, 0x72, 0xba,
		0x2a, 0xe9, 0x0e, 0xbf, 0x6e, 0xb4, 0xfc, 0xa4, 0x37, 0xda, 0x59, 0x7e, 0x64, 0x53, 0x99, 0xc6,
		0x45, 0xd5, 0x32, 0xbc, 0x22, 0x1f, 0xb2, 0x33, 0xa1, 0x9f, 0x14, 0xd7, 0xce, 0x8a, 0xc3, 0xd4,
		0x27, 0xd3, 0x7e, 0x8b, 0xce, 0x89, 0x35, 0x70, 0xeb, 0x7e, 0x01, 0x6f, 0x66, 0xa9, 0xce, 0x57,
		0xf6, 0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x59, 0xaa, 0x1d, 0x1b, 0x01, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) SemaphoreAPIYARPCClient {
			return NewSemaphoreAPIYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
