// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uber/cadence/api/v1/service_semaphore.proto

package apiv1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CreateSemaphoreRequest struct {
	Domain        string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	SemaphoreName string `protobuf:"bytes,2,opt,name=semaphore_name,json=semaphoreName,proto3" json:"semaphore_name,omitempty"`
	// Total number of tokens. Must be positive.
	Capacity int32 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Optional. Number of tokens in each bucket, the server picks a default if unset, and rejects values
	// above its maximum.
	BucketCapacity       int32    `protobuf:"varint,4,opt,name=bucket_capacity,json=bucketCapacity,proto3" json:"bucket_capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSemaphoreRequest) Reset()         { *m = CreateSemaphoreRequest{} }
func (m *CreateSemaphoreRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSemaphoreRequest) ProtoMessage()    {}
func (*CreateSemaphoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60f52eba354a86a4, []int{0}
}
func (m *CreateSemaphoreRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateSemaphoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateSemaphoreRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateSemaphoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSemaphoreRequest.Merge(m, src)
}
func (m *CreateSemaphoreRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateSemaphoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSemaphoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSemaphoreRequest proto.InternalMessageInfo

func (m *CreateSemaphoreRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *CreateSemaphoreRequest) GetSemaphoreName() string {
	if m != nil {
		return m.SemaphoreName
	}
	return ""
}

func (m *CreateSemaphoreRequest) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *CreateSemaphoreRequest) GetBucketCapacity() int32 {
	if m != nil {
		return m.BucketCapacity
	}
	return 0
}

type CreateSemaphoreResponse struct {
	// The semaphore as stored, with defaults filled in.
	Semaphore            *Semaphore `protobuf:"bytes,1,opt,name=semaphore,proto3" json:"semaphore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateSemaphoreResponse) Reset()         { *m = CreateSemaphoreResponse{} }
func (m *CreateSemaphoreResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSemaphoreResponse) ProtoMessage()    {}
func (*CreateSemaphoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60f52eba354a86a4, []int{1}
}
func (m *CreateSemaphoreResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateSemaphoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateSemaphoreResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateSemaphoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSemaphoreResponse.Merge(m, src)
}
func (m *CreateSemaphoreResponse) XXX_Size() int {
	return m.Size()
}
func (m *CreateSemaphoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSemaphoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSemaphoreResponse proto.InternalMessageInfo

func (m *CreateSemaphoreResponse) GetSemaphore() *Semaphore {
	if m != nil {
		return m.Semaphore
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateSemaphoreRequest)(nil), "uber.cadence.api.v1.CreateSemaphoreRequest")
	proto.RegisterType((*CreateSemaphoreResponse)(nil), "uber.cadence.api.v1.CreateSemaphoreResponse")
}

func init() {
	proto.RegisterFile("uber/cadence/api/v1/service_semaphore.proto", fileDescriptor_60f52eba354a86a4)
}

var fileDescriptor_60f52eba354a86a4 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xcd, 0x4e, 0x32, 0x31,
	0x14, 0x4d, 0xbf, 0x4f, 0x89, 0x54, 0x85, 0xa4, 0x46, 0x20, 0x2c, 0x26, 0x04, 0x63, 0x24, 0x41,
	0xdb, 0x0c, 0x2e, 0x75, 0x23, 0xac, 0xdc, 0x18, 0x02, 0x0b, 0x13, 0x37, 0xa4, 0x53, 0x6e, 0xa0,
	0x91, 0x4e, 0xcb, 0x4c, 0x67, 0x12, 0x13, 0x1f, 0xc5, 0x07, 0x72, 0xe9, 0x23, 0x18, 0x9e, 0xc4,
	0x30, 0x8c, 0xc5, 0x9f, 0x59, 0xb8, 0xbc, 0xe7, 0x9e, 0x73, 0xee, 0xc9, 0x3d, 0xb8, 0x9b, 0x04,
	0x10, 0x31, 0xc1, 0xa7, 0x10, 0x0a, 0x60, 0xdc, 0x48, 0x96, 0xfa, 0x2c, 0x86, 0x28, 0x95, 0x02,
	0x26, 0x31, 0x28, 0x6e, 0xe6, 0x3a, 0x02, 0x6a, 0x22, 0x6d, 0x35, 0x39, 0x5a, 0x93, 0x69, 0x4e,
	0xa6, 0xdc, 0x48, 0x9a, 0xfa, 0xcd, 0x93, 0x62, 0x87, 0x6f, 0xca, 0xf6, 0x0b, 0xc2, 0xb5, 0x41,
	0x04, 0xdc, 0xc2, 0xf8, 0x73, 0x33, 0x82, 0x65, 0x02, 0xb1, 0x25, 0x35, 0x5c, 0x9a, 0x6a, 0xc5,
	0x65, 0xd8, 0x40, 0x2d, 0xd4, 0x29, 0x8f, 0xf2, 0x89, 0x9c, 0xe2, 0x8a, 0x73, 0x99, 0x84, 0x5c,
	0x41, 0xe3, 0x5f, 0xb6, 0x3f, 0x74, 0xe8, 0x1d, 0x57, 0x40, 0x9a, 0x78, 0x4f, 0x70, 0xc3, 0x85,
	0xb4, 0x4f, 0x8d, 0xff, 0x2d, 0xd4, 0xd9, 0x1d, 0xb9, 0x99, 0x9c, 0xe1, 0x6a, 0x90, 0x88, 0x47,
	0xb0, 0x13, 0x47, 0xd9, 0xc9, 0x28, 0x95, 0x0d, 0x3c, 0xc8, 0xd1, 0xf6, 0x3d, 0xae, 0xff, 0x4a,
	0x17, 0x1b, 0x1d, 0xc6, 0x40, 0xae, 0x71, 0xd9, 0x1d, 0xcc, 0x12, 0xee, 0xf7, 0x3c, 0x5a, 0xf0,
	0x07, 0xba, 0x95, 0x6e, 0x05, 0xbd, 0x67, 0x7c, 0xe0, 0xf0, 0x9b, 0xe1, 0x2d, 0x59, 0xe0, 0xea,
	0x8f, 0x43, 0xa4, 0x5b, 0xe8, 0x56, 0xfc, 0xac, 0xe6, 0xf9, 0xdf, 0xc8, 0x9b, 0xec, 0xfd, 0xe5,
	0xeb, 0xca, 0x43, 0x6f, 0x2b, 0x0f, 0xbd, 0xaf, 0x3c, 0x84, 0xeb, 0x42, 0xab, 0x22, 0x79, 0xff,
	0xd8, 0x29, 0xc7, 0x9b, 0xe2, 0x87, 0xeb, 0xce, 0x86, 0xe8, 0xc1, 0x9f, 0x49, 0x3b, 0x4f, 0x02,
	0x2a, 0xb4, 0x62, 0x5f, 0x5b, 0xbe, 0x90, 0xd3, 0x05, 0x9b, 0x69, 0x96, 0x75, 0x9b, 0x57, 0x7e,
	0xc5, 0x8d, 0x4c, 0xfd, 0xa0, 0x94, 0x61, 0x97, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x1e,
	0x9a, 0x63, 0x58, 0x02, 0x00, 0x00,
}

func (m *CreateSemaphoreRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateSemaphoreRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateSemaphoreRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.BucketCapacity != 0 {
		i = encodeVarintServiceSemaphore(dAtA, i, uint64(m.BucketCapacity))
		i--
		dAtA[i] = 0x20
	}
	if m.Capacity != 0 {
		i = encodeVarintServiceSemaphore(dAtA, i, uint64(m.Capacity))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SemaphoreName) > 0 {
		i -= len(m.SemaphoreName)
		copy(dAtA[i:], m.SemaphoreName)
		i = encodeVarintServiceSemaphore(dAtA, i, uint64(len(m.SemaphoreName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintServiceSemaphore(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateSemaphoreResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateSemaphoreResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateSemaphoreResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Semaphore != nil {
		{
			size, err := m.Semaphore.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintServiceSemaphore(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintServiceSemaphore(dAtA []byte, offset int, v uint64) int {
	offset -= sovServiceSemaphore(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CreateSemaphoreRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovServiceSemaphore(uint64(l))
	}
	l = len(m.SemaphoreName)
	if l > 0 {
		n += 1 + l + sovServiceSemaphore(uint64(l))
	}
	if m.Capacity != 0 {
		n += 1 + sovServiceSemaphore(uint64(m.Capacity))
	}
	if m.BucketCapacity != 0 {
		n += 1 + sovServiceSemaphore(uint64(m.BucketCapacity))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CreateSemaphoreResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Semaphore != nil {
		l = m.Semaphore.Size()
		n += 1 + l + sovServiceSemaphore(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovServiceSemaphore(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozServiceSemaphore(x uint64) (n int) {
	return sovServiceSemaphore(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CreateSemaphoreRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServiceSemaphore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateSemaphoreRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateSemaphoreRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SemaphoreName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SemaphoreName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capacity", wireType)
			}
			m.Capacity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Capacity |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BucketCapacity", wireType)
			}
			m.BucketCapacity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BucketCapacity |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipServiceSemaphore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateSemaphoreResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServiceSemaphore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateSemaphoreResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateSemaphoreResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Semaphore", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Semaphore == nil {
				m.Semaphore = &Semaphore{}
			}
			if err := m.Semaphore.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServiceSemaphore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipServiceSemaphore(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowServiceSemaphore
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthServiceSemaphore
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupServiceSemaphore
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthServiceSemaphore
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthServiceSemaphore        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowServiceSemaphore          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupServiceSemaphore = fmt.Errorf("proto: unexpected end of group")
)
